### ISSUE TITLE
Leap Day 02-29-2020 raises KeyError

### ISSUE THREAD

**Issue by caseytirshfield** [quantopian/trading_calendars#128]
Calling `get_calendar('XNYS').previous_session_label(datetime.date(2020, 2, 29))` raises a `KeyError`.

**Comment by ssanderson** [comment]
I think this is unrelated to leap day. The issue here is just that `previous_session_label` requires that its input is a trading session, and feb 29 was a saturday. The same error also gets raised for March 1st:

```
In [6]: c.previous_session_label(pd.Timestamp('2020-03-02'))
Out[6]: Timestamp('2020-02-28 00:00:00+0000', tz='UTC', freq='C')

In [7]: c.previous_session_label(pd.Timestamp('2020-03-01'))
...
KeyError: Timestamp('2020-03-01 00:00:00+0000', tz='UTC')
```

Closing this as as-designed. Feel free to reopen if you think there's something I've missed.
