### ISSUE TITLE
Trading date is one year larger

### ISSUE THREAD

**Issue by kychanbp** [quantopian/trading_calendars#37]
When I tried to get the US calendar and call all_sessions.

The date returned is one year larger.

**Comment by jmccorriston** [comment]
I believe this is related to https://github.com/quantopian/trading_calendars/issues/36, where the default end date of a calendar is one year in the future. I'm going to close this issue since it is so similar to https://github.com/quantopian/trading_calendars/issues/36, and I believe allowing you to override the end date in `get_calendar` would solve the confusion.

If you believe that I misunderstood the problem you encountered, please let me know!

P.S. Sorry for the very slow response time on this :(
