### ISSUE TITLE
Change in trading hours in Brazilian SE

### ISSUE THREAD

**Issue by willianpaixao** [quantopian/trading_calendars#96]
Starting tomorrow, BVMF will extend its trading hours by one hour. [[1]](http://www.b3.com.br/en_us/news/new-trading-hours-8AE490C86E13936B016E23EB3C4E67E4.htm)[[2]](http://www.b3.com.br/en_us/news/new-trading-hours-8AE490C86E13936B016E23EB3C4E67E4.htm)

**Comment by jmccorriston** [comment]
Thanks for reporting this! I tried reading through the resource you linked, but it's not clear to me if this is a permanent or temporary change. Do you have any more information or details on the change? If it's related to daylight saving time ending in the US, I'm wondering if this is just a seasonal change.

**Comment by willianpaixao** [comment]
It's a permanent change. (no related to season or daylight saving)
I looked through the file and thought about changing and just creating a pull request instead of an issue, but I'm not sure how to add this change without affecting past dates (by having a close time starting from a specific date).

If you can assure me that it's simply bumping the number [here](https://github.com/quantopian/trading_calendars/blob/a2a60af3e040ef2cb785c28b361fb431526ce12d/trading_calendars/exchange_calendar_bvmf.py#L185), I can do it.

**Comment by jmccorriston** [comment]
You're right. I think the change is a bit more complicated than just changing the number so that the history isn't changed. I think we'll have to do something a little more involved to capture this change.

Do you have any other sources explaining that this is a permanent change? I followed the source you linked (http://www.b3.com.br/en_us/news/new-trading-hours-8AE490C86E13936B016E23EB3C4E67E4.htm), and it starts by saying "Owing to the end of daylight saving time in the United States on November 03, 2019". I also looked at the longer document (http://www.b3.com.br/data/files/EC/B1/BD/2D/A8B4D6107C4D14D6AC094EA8/OC%20070-2019%20Novos%20Hor%C3%A1rios%20de%20Negocia%C3%A7%C3%A3o%20-%20Segmento%20BMF%20e%20Bovespa%20(ING).pdf), but I don't see any clarifying language in there either.

**Comment by jmccorriston** [comment]
As for the change itself, @dmichalowicz pointed me to [this example](https://github.com/quantopian/trading_calendars/blob/a2a60af3e040ef2cb785c28b361fb431526ce12d/trading_calendars/exchange_calendar_xhkg.py#L124-L127) in the Hong Kong calendar where we implemented a change in the open time. Would you be willing to make a similar change to the Brazil calendar like that?

**Comment by willianpaixao** [comment]
Yes, in fact the document is not clear. I went back to the original article I read [[1]](https://www.infomoney.com.br/mercados/bolsa-muda-horario-de-negociacao-a-partir-de-segunda-feira/) and you're right. Another [article](https://economia.uol.com.br/cotacoes/noticias/redacao/2019/11/04/bolsa-horario.htm) (but also in portuguese).

The change in the trading hours is due to a recent law our stupid president signed terminating daylight saving in whole Brazil for no reason. [[2]](https://g1.globo.com/politica/noticia/2019/04/25/bolsonaro-assina-decreto-que-acaba-com-o-horario-de-verao.ghtml)

So the the Brazilian Stock Exchange was forced to change the trading hours to avoid a mismatch between the US Stock Exchanges. So the change is permanent until hopefully next president revoke this non-sense law.

And yes, I can surely make a pull request following that example.
